routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('home');
})->name('home');

// customer Registration
Route::controller(\App\Http\Controllers\CustomerController::class)
    ->prefix('')
    ->name('customer.')
    ->group(function () {
        Route::get('/register', 'show')->name('register');
        Route::post('/register', 'store');
    });

Route::controller(\App\Http\Controllers\AdminController::class)
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {

        // admin auth routes
        Route::middleware(['guest'])
            ->group(function () {
                Route::get('login', 'login')->name('login');
                Route::post('login', 'auth');
                Route::post('logout', 'logout')
                    ->name('logout')
                    ->withoutMiddleware(['guest'])
                    ->middleware(['admin']);
            });

        // admin customize customer
        Route::middleware(['admin'])
            ->prefix('customer')
            ->name('customer.')
            ->group(function () {
                Route::get('', 'index')->name('index');
                Route::get('update/{id}', 'edit')->name('update');
                Route::put('update/{id}', 'update');
                Route::delete('destroy/{id}', 'destroy')->name('destroy');
            });
    });

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Hash;

class Customer extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function isAdmin()
    {
        return true;
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;

class AdminController extends Controller
{
    public function login()
    {
        return view('admin.login');
    }

    public function auth(Request $request)
    {
        $credentials = $request->only('email', 'password');

        if (Auth::attempt($credentials))
            return redirect()->intended('/admin/customer');

        else
            return Redirect::back()->withErrors(['message' => 'Invalid credentials']);
    }

    public function logout()
    {
        Auth::logout();

        return Redirect::route('home');
    }

    public function index()
    {
        $customers = Customer::all();
        return view('admin.customer.index', compact('customers'));
    }

    public function edit(Request $request, $id)
    {
        $customer = Customer::find($id);
        return view('admin.customer.update', compact(['customer']));
    }

    public function update(Request $request, $id)
    {
        Customer::where(['id' => $id])->update([
            'name' => $request->name,
            'email' => $request->email,
        ]);

        return Redirect::route('admin.customer.index')->withErrors(['message' => 'Update Successfully']);
    }

    public function destroy($id)
    {
        $customer = Customer::findOrFail($id);
        $customer->delete(); // Perform the soft delete

        return Redirect::route('admin.customer.index')
            ->withErrors(['message' => 'Delete Successfully']);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CustomerStoreRequest;
use App\Models\Customer;
use Illuminate\Support\Facades\Redirect;

class CustomerController extends Controller
{
    public function show()
    {
        return view('customer.register');
    }

    public function store(CustomerStoreRequest $request)
    {
        Customer::create($request->all());
        return Redirect::route('home');
    }

}

resources/views/admin/customer/index.blade.php
@extends('layouts.admin')

@section('content')
  <section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-12">
          <div class="card rounded-3">
            <div class="card-body p-4">

              <h5 class="mb-0"><a href="/"><i class="fas fa-home me-2"></i></a>List Customers</h5>


              <div style="max-height: 400px; overflow-y: auto;">
                <div class="d-flex flex-row align-items-center mb-4">
                  <div class="flex-fill mb-0">
                    <div class="list-group list-group-light">
                      @foreach($errors->all() as $error)
                        <a href="#" class="list-group-item list-group-item-action px-3 border-0 rounded-3 mb-2 list-group-item-secondary">
                          {{ $error }}
                        </a>
                      @endforeach
                    </div>
                  </div>
                </div>

                <table class="table mb-4">
                  <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  @foreach ($customers as $customer)
                    <tr>
                      <th scope="row">{{ $customer->id }}</th>
                      <td>{{ $customer->name }}</td>
                      <td>{{ $customer->email }}</td>
                      <td>
                        <form action="{{ route('admin.customer.destroy', $customer->id) }}" method="post" class="d-inline">
                          @csrf
                          @method('DELETE')
                          <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        <a href="{{ route('admin.customer.update', $customer->id) }}" class="d-inline">
                          <button class="btn btn-success ms-1">Update</button>
                        </a>
                      </td>
                    </tr>
                  @endforeach
                  </tbody>
                </table>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/customer/update.blade.php
@extends('layouts.admin')

@section('content')
  <section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Edit Customer</p>

                  <form action="{{ route('admin.customer.update', $customer->id) }}" method="post" class="mx-1 mx-md-4">
                    @csrf
                    @method('PUT')
                    <div class="d-flex flex-row align-items-center mb-4">
                      <div class="flex-fill mb-0">
                        <div class="list-group list-group-light">
                          @foreach($errors->all() as $error)
                            <a href="#" class="list-group-item list-group-item-action px-3 border-0 rounded-3 mb-2 list-group-item-secondary">
                              {{ $error }}
                            </a>
                          @endforeach
                        </div>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" id="form3Example1c" class="form-control" name="name" value="{{ old('name', $customer->name) }}" />
                        <label class="form-label" for="form3Example1c">Your Name</label>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="email" id="form3Example3c" class="form-control" name="email" value="{{ old('email', $customer->email) }}" />
                        <label class="form-label" for="form3Example3c">Your Email</label>
                      </div>
                    </div>

                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Update</button>
                    </div>

                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/login.blade.php
@extends('layouts.admin')

@section('content')
  <section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-12 col-xl-10">
          <div class="card">
            <div class="card-header p-3">
              <h5 class="mb-0"><a href="/"><i class="fas fa-home me-2"></i></a>Admin Login</h5>
            </div>
            <div class="card-body d-flex justify-content-center align-items-center">
              <form class="col-5" action="{{ route('admin.login') }}" method="post">
                @csrf
                <div class="d-flex flex-row align-items-center mb-4">
                  <div class="flex-fill mb-0">
                    <div class="list-group list-group-light">
                      @foreach($errors->all() as $error)
                        <a href="#" class="list-group-item list-group-item-action px-3 border-0 rounded-3 mb-2 list-group-item-danger">
                          {{ $error }}
                        </a>
                      @endforeach
                    </div>
                  </div>
                </div>
                <div class="form-outline mb-4">
                  <input type="email" id="form2Example1" class="form-control" name="email"/>
                  <label class="form-label" for="form2Example1">Email address</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="password" id="form2Example2" class="form-control" name="password"/>
                  <label class="form-label" for="form2Example2">Password</label>
                </div>

                <div class="row mb-4">
                  <div class="col d-flex justify-content-center">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked/>
                      <label class="form-check-label" for="form2Example31"> Remember me </label>
                    </div>
                  </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/customer/register.blade.php
@extends('layouts.guest')

@section('content')
  <section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                  <form action="/register" method="POST" class="mx-1 mx-md-4">
                    @csrf
                    <div class="d-flex flex-row align-items-center mb-4">
                      <div class="flex-fill mb-0">
                        <div class="list-group list-group-light">
                          @foreach($errors->all() as $error)
                            <a href="#" class="list-group-item list-group-item-action px-3 border-0 rounded-3 mb-2 list-group-item-danger">
                              {{ $error }}
                            </a>
                          @endforeach
                        </div>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" id="form3Example1c" class="form-control" name="name" value="{{ old('name') }}" />
                        <label class="form-label" for="form3Example1c">Your Name</label>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="email" id="form3Example3c" class="form-control" name="email" value="{{ old('email') }}" />
                        <label class="form-label" for="form3Example3c">Your Email</label>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" id="form3Example4c" class="form-control" name="password" />
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" id="form3Example4cd" class="form-control" name="password_confirmation" />
                        <label class="form-label" for="form3Example4cd">Repeat your password</label>
                      </div>
                    </div>

                    <div class="form-check d-flex justify-content-center mb-5">
                      <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                      <label class="form-check-label" for="form2Example3">
                        I agree all statements in <a href="#!">Terms of service</a>
                      </label>
                    </div>

                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Register</button>
                    </div>

                  </form>

                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                       class="img-fluid" alt="Sample image">

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/home.blade.php
@extends('layouts.guest')

@section('content')
  <section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-12 col-xl-10">
          <div class="card">
            <div class="card-header p-3">
              <div class="d-flex justify-content-between align-items-center">
                <h5 class="mb-0"><i class="fas fa-home me-2"></i>Home Page</h5>

                @if(Auth::check())
                  <form action="{{ route('admin.logout') }}" method="post" class="d-inline">
                    @csrf
                    <button type="submit" class="btn btn-danger ms-1">LOGOUT</button>
                  </form>
                @endif
              </div>
            </div>

            <div class="card-body" data-mdb-perfect-scrollbar="true" style="position: relative; height: 400px">
              <div class="row mb-4">
                <div class="col">
                  <a href="{{ route('customer.register') }}">Customer Registration</a>
                </div>
              </div>

              @if(!Auth::check())
                <div class="row mb-4">
                  <div class="col">
                    <a href="{{ route('admin.login') }}">Admin Login</a>
                  </div>
                </div>
              @else
                <div class="row mb-4">
                  <div class="col">
                    <a href="{{ route('admin.customer.index') }}">Customer Management</a>
                  </div>
                </div>
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Font Awesome -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
  />
  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
  />
  <!-- MDB -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.css"
    rel="stylesheet"
  />


  <title>Platinum Communications</title>
</head>
<body>
@yield('content')
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.js"
></script>
</body>
</html>

resources/views/layouts/guest.blade.php
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Font Awesome -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
  />
  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
  />
  <!-- MDB -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.css"
    rel="stylesheet"
  />


  <title>Platinum Communications</title>
</head>
<body>
@yield('content')
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.js"
></script>
</body>
</html>